@startuml
'https://plantuml.com/class-diagram
class Batiment{
String nomBat
ajouterPiece(Piece piece)
mettreAJourPiece(Piece piece)
retirerPiece(Piece piece)
String getNomBat()
int getNbPieces()
Piece getPiece(int index)
List<Piece> getListPieces()
Boolean pieceIsInBat(String nomPiece)
Piece getPiece(String nomPiece)
Piece getPiece2(String nom)
supprimerTout()
}
class Monde{
ajouterBatiment()
getBatiment()
}

class Piece {
String nom;
int noPiece;
Mur [] tabMur = new Mur[4];
Mur getMur(int i)
String getNom()
ajouterMur(Mur mur)
modifierMur(Mur mur)
setNom(String nom)
setNoPiece(int noPiece)
}
class Sortie{
Piece piece
int noSortie
int x
int y
int x2
int y2
Rect rect
String getNomPiece()
int getNoSortie()
Rect getRect()
}

class Mur {
int noMur
String nomPhoto
int getNoMur()
String getNomPhoto()
Sortie getSortie(int index)
setPhoto(String nomPhoto)
ajouterSortie(Sortie sortie)
supprimerPorte(Sortie porte)
}
'class MainActivity{
'Button Construction
'Button Simulation
'onCreate()
'}
Monde--"*"Batiment
Batiment--"*"Piece
Piece--"4"Mur
Sortie -- "1" Piece
Mur--"                  *"Sortie

@enduml