@startuml
'https://plantuml.com/class-diagram
class Batiment{
String nomBat
ajouterPiece(Piece piece)
getNbPieces()
}

class Piece {
String nomPiece
int noPiece
int nbSorties
Piece [] zonesSorties
getZonesSorties()
}
class Sortie{
int noSortie
Rect zoneSortie
}

class Mur {
int noMur
ImageView photo
}
'class MainActivity{
'Button Construction
'Button Simulation
'onCreate()
'}

Batiment--"*"Piece
Piece--"4"Mur
Sortie -- "1" Piece
Mur--"                  *"Sortie

@enduml